image: harbor.shopeemobile.com/shopee-fe/web-frontend-gitlab-runner:node16.18.1-pnpm6.32.25-sdc0.1.834-chrome107.0.5304.121

stages:
  - test
  - publish

before_script:
  - npm install

pages:
  stage: publish

  script:
    - npm run build-storybook:gitlab
  artifacts:
    paths:
    - public
  
  only:
    - tags 
  except:
    - branches

test:
  stage: test
  script:
    - npm run test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'